### ISSUE TITLE
generating star names and tags based on files name

### ISSUE THREAD

**Issue by adviser23** [pornganizer/PGV5#1]
I have too many files, which I named them in the following rule:
[females][males if the scene is straight][name of scene][tags][studio][quality]
all parts are separated by the comma, below there's some example .....
[ANIKKA ALBRITE, TORI BLACK, ABIGAIL MAC, JENNA SATIVA, ANA FOXXX][][][lesbian,anal,orgy,assLicking,scissoring,squirt,strapon,dp][LesbianX][720]
[Aletta Ocean, Kayla Green][Unkown][][threesome,perfectBody][][720]

plz, add the feature to create or update the database based on those files name ;)

+ don`t forget to solve the resolution problem on a 13.3-inch laptop with 1920*1080, I think just making your app`s screen resizable will fix the problem 👍

**Comment by pornganizer** [comment]
if any of those names or tags are already in your PG database, it will tag the files automatically
PG currently create tags automatically.
