### ISSUE TITLE
"Export Cover Images To Folder" button

### ISSUE THREAD

**Issue by GernBlanston12** [pornganizer/PGV5#25]
For each of DVD, Star, Performer, Website, Category and Theme, a button to export all primary/main profile images to a separate folder.  This could be used to quickly create image packs for users to share, as it would export only the main profile pics, not other jpgs and dross that might be associated to the given object or be resident in whatever cache folder is in use. My Websites folder, for example, is littered with .png logos and other leftovers I used to create my Website images. I ended up building similar function in a script using exported/massaged tables, but it could be done easily in the program.

**Comment by GernBlanston12** [comment]
Another useful function to go along with this would be a "rename cover image to Star (Website, DVD, etc) name", as when preparing an image pack to share, you want a pristine name, not "Jessa R Tushy beach babe.jpg" like you might have for her profile pic.

**Comment by pornganizer** [comment]
OK so at this point in time I'm not really focused on adding any utility to facilitate sharing things outside of PG, like creating image packs.  Image support in general is lacking in PG, and I think there is a lot of room for improvement (including something like this) when I get to it.
