### ISSUE TITLE
Import PGV4 data to V5 doesn't work

### ISSUE THREAD

**Issue by xwanda23x** [pornganizer/PGV5#29]
Hi,
I follow all the steps with DB Browser for SQlite, then it creates a file called "pgv5_db.realm". But when i open the new data base with PGV5 nothing appears.

**Comment by eleanorripley** [comment]
Seconded. I imported my data from V3, it showed up nicely in V4, but V5 is empty and crashes after a while.

**Comment by pornganizer** [comment]
this is an ongoing issue i'm trying to resolve.

if you could send me a .zip file of your exported JSON folders, i can look into it.

**Comment by pornganizer** [comment]
please try this again with the latest version

**Comment by xwanda23x** [comment]
Still does'nt
Just after i import data from json file PG5 crashes
[JSON.zip](https://github.com/pornganizer/PGV5/files/4774231/JSON.zip)

**Comment by pornganizer** [comment]
are you 100% sure you are running the most up to date version? i was able to import your v4 data without any problems
![image](https://user-images.githubusercontent.com/21695807/84569099-face4600-ad51-11ea-9da0-4e283223011c.png)

**Comment by xwanda23x** [comment]
Yes i'm pretty sure i have the latest one
here what happens when i import. Maybe i do something wrong.
[Screen Record pg.zip](https://github.com/pornganizer/PGV5/files/4775167/Screen.Record.pg.zip)

**Comment by pornganizer** [comment]
can you show your "About" screen please

**Comment by xwanda23x** [comment]
![Capture](https://user-images.githubusercontent.com/47448274/84578122-a6af7a00-adc2-11ea-8bf7-8e2339b9c0ab.JPG)

**Comment by pornganizer** [comment]
hm. damn. im wondering if its a localization issue, i see your OS isn't english

**Comment by pornganizer** [comment]
![image](https://user-images.githubusercontent.com/21695807/84579353-02fea380-ad9b-11ea-845e-6a70052a623e.png)
could i ask you to open the Windows Event Viewer, clear the logs, then perform the import? this will generate some error logs in this pane, and if you could send ALL the text of ALL the errors that show up here immediately after the crash, I might be able to figure this out.

**Comment by xwanda23x** [comment]
[Nouveau document texte.txt](https://github.com/pornganizer/PGV5/files/4775887/Nouveau.document.texte.txt)
[Nouveau document texte (2).txt](https://github.com/pornganizer/PGV5/files/4775888/Nouveau.document.texte.2.txt)
[Nouveau document texte (3).txt](https://github.com/pornganizer/PGV5/files/4775889/Nouveau.document.texte.3.txt)

**Comment by xwanda23x** [comment]
Still not working with the new version
Here what i get now
![Capture](https://user-images.githubusercontent.com/47448274/86885619-df0e5380-c0f5-11ea-9620-b7fff89b45f2.JPG)

**Comment by pornganizer** [comment]
are you on windows 7?
this seems like more like a file permission problem then an import problem
my guess right now is that PG is failing to create the database file.

Are you able to create a new database instead of importing from v4?

**Comment by xwanda23x** [comment]
No i'm on windows 10
Yes i can create new database and import scenes

**Comment by xwanda23x** [comment]
Sorry to bother you, really ;) but if there is no solution maybe you can just send me the database after you importing from my json folder ? (if it's possible)
really sorry to ask that, you do such good work

**Comment by pornganizer** [comment]
i've added yet more debugging stuff to the import process. try and hold off
until the next update

**Comment by pornganizer** [comment]
have you had a chance to try the newest update?

**Comment by xwanda23x** [comment]
![Capture](https://user-images.githubusercontent.com/47448274/87509886-c90f0e80-c672-11ea-8768-1c83b435cf02.JPG)

**Comment by pornganizer** [comment]
ok so the problem is not the actual import process, it is that PG is unable to create a file at the path you are specifying.

you can try to "fix" this by manually creating a file of the same name, and then overwriting when performing the import

You can perhaps also try specifying a path on a different drive or folder

I'd also recommend ensuring that your windows is FULLY up to date

I have just released yet another update that tries to provide more information about why that file creation is failing

**Comment by xwanda23x** [comment]
i tried to overwriting with a same file name but it crashes
I tried to create the file on differents drives and folders but:
![Capture](https://user-images.githubusercontent.com/47448274/87546126-4fdede00-c6a9-11ea-9f37-ea2f83cbe804.JPG)

**Comment by pornganizer** [comment]
thanks for your patience. i will sort this out. it does look like the
problem is on my end, i'm just not sure why no one else has this issue.

**Comment by zelpi** [comment]
hi there. i get the same window when i click on the json-folder to make the import.
when i load the created realm-file (which obviously is empty because tags shown are all zero) the program window simply disappears.

**Comment by pornganizer** [comment]
could both of you please try the latest update
@zelpi @xwanda23x

**Comment by xwanda23x** [comment]
It's working
Thanks a lot

**Comment by zelpi** [comment]
Also on my side. Thank you!
