### ISSUE TITLE
Any way to bulk add content?

### ISSUE THREAD

**Issue by DankMemeGuy** [pornganizer/PGV5#34]
I have a folder of celebs. I would like to just select all the folders and have PGV5 automatically add all those folders with the ability to select who the person is, or perhaps have it suggested from the folder name.

**Comment by pornganizer** [comment]
When you import content, the paths of any files are compared against tags that exist in your PG database. 
When you add a tag, all content in your PG database is checked for that tag.

This means you can add your folder, then add each Star to PG, or the other way around. 

Currently, the only way to mass import is via images. If you have an image named "Riley Reid.jpg", one of the import options allows you to import the image and create the star.

Better mass importing options are coming soon. Ideally, how would you want to be able to import your content? You didn't really specify what format stuff inside your folder is.

**Comment by pornganizer** [comment]
You can now add stars in bulk via a json file

https://github.com/pornganizer/PGV5/wiki

**Comment by DankMemeGuy** [comment]
Right now my structure is ~/Celebs/Name/~ and each folder contains pictures and videos. I would hope to maintain the original file name, but have all the content inside the folder attached to the Celeb's name. If that makes sense?

I'm not sure how to use it right now. When I drag and drop a folder it doesn't import all the content, but I haven't looked too much into what's happening or if there's just so much content that it's lagging out etc. Do you know what limits this can hit? How much RAM one should have. How many pictures/videos, etc?

**Comment by pornganizer** [comment]
PG will import all image and video files in an imported folder, nested or not.
When you drag content into PG, a little spinner appears in the bottom right. When it's ready, it will change to an import button. All the dragged in content should be visible in this window.

There are no real limits, it will just take longer the more you import.  

As far as tagging your content, you can add any Stars you want either before or after the import, but there's no way for PG to automatically parse them out of the file path of any imported content. Adding content to PG triggers an auto-tag pass for any other content deemed relevant.
