### ISSUE TITLE
Search by star attributes

### ISSUE THREAD

**Issue by zelpi** [pornganizer/PGV5#36]
I created some star attributes like hair and eye color and height and weight (with custom values).
I'd like to put a filter for example on blue eyed blondes or show only stars with height between 150 and 170 cm. 
Is or will it be possible to implement search for manually created star Attributes?

Btw. a great piece of software, thanks for all the efforts!

**Comment by pornganizer** [comment]
search by attributes is coming

**Comment by zelpi** [comment]
Some suggestions for the star profile: Start and end date should be only year because an exact date often is not known. And links for the person also should be possible to insert as it was in PGV4. It would be nice to see all the informations directly in the profile area without open the profile window.

**Comment by pornganizer** [comment]
i'll think about adding links back

**Comment by zelpi** [comment]
Tested the newest file. 
Created attributes for profiles . Visible in the left searching bar. But when I choose one assigned tag, no items (scenes/profiles) are displayed.

**Comment by zelpi** [comment]
Ok, now functioning, thanks!

**Comment by zelpi** [comment]
Can you please implement the possibility to edit attributes and their values (otherwise they have to be always deleted and created again) ?

**Comment by zelpi** [comment]
Can you please also make possible to assign more than one value to a star inside of an attribute ?

**Comment by pornganizer** [comment]
i'm going to close this as you can now search by attributes
i'll keep your other requests in mind
