### ISSUE TITLE
ability to add additional categories & stars to a  to a bookmark (edit bookmark in the main screen)

### ISSUE THREAD

**Issue by Porndli** [pornganizer/PGV5#39]
At the moment the bookmarks are not  filterable by star, it would also be great to refine them a  bit by adding additional categories . that are also filterable. Would make Porn collecting a lot of fun too...tagging all the fun bits :D

**Comment by pornganizer** [comment]
while the ability to filter bookmarks by specific criteria is lacking, bookmarks already inherit star and category information. when you apply a bookmark to a scene, you choose a category. the bookmark will inherit that category as well as any stars added to the scene.
