### ISSUE TITLE
4 apparently little bugs

### ISSUE THREAD

**Issue by zelpi** [pornganizer/PGV5#42]
1. Inserting in a star profile window a date in "birth date" and "career date", the program shows after closing and re-opening a date which is one day before.
2. Opening a scene profile window, it shows the realease date as one day before the correct one (which is part of my filename and which is displayed correctly next to the "Add category" icon).
3. The "DVDS" section shows in some cases pictures (thumbs) that are connected with the DVD but not represent the cover.
4. Adding a scene and inserting a description results after re-opening the program in losing that description. Only after re-opening and adding the description, it stays.

**Comment by pornganizer** [comment]
1,2 - fixed in 0.1.247
3 - this is expected behavior. 0.1.246 introduced image sets for DVDs allowing you to control which images appear as thumb.
4 - fixed in 0.1.246
