### ISSUE TITLE
Very high mem and CPU usage

### ISSUE THREAD

**Issue by anteac** [pornganizer/PGV5#44]
Im using PG v5, v-.1.244.0, as this is the most stable for me.
But at random times vid previews take like 10 sec to load, Scrolling becomes very slow, Windows throws an error "Application PG5.exe is blocked for access to graphical hardware.

but soem days I have no issues with this version> Do you expect whats wrong?

thx

**Comment by pornganizer** [comment]
try increasing your tile sizes so less content loads at once
