### ISSUE TITLE
Filtering by rating & missing details in details pane

### ISSUE THREAD

**Issue by anti-alias-11** [pornganizer/PGV5#45]
- Filtering by star rating (1-5 stars) doesn't seem to do anything? there's also a "greater than or equal" symbol next to it that can't be changed.
- Recent update removed the ability to see categories & related images in the details pane, hopefully that wasn't intentional as there's no way to see them otherwise? at least the categories associated with the file. I know you can see the images by enabling the toggle at the top but having the associated pictures/thumbnails in the details pane was a nice touch.

**Comment by pornganizer** [comment]
the latest version allows you to filter by rating

as for not being able to see categories and images in the details pane, are you sure you don't just have them toggled off via the bottom toggle panel?

**Comment by anti-alias-11** [comment]
Yep my bad I had them toggled off, although I don't remember ever touching the buttons so I think they all got auto toggled off at some point, maybe when I updated... who knows.

Also by the latest version you mean v0.1.002? I currently have version v0.1.256 and filtering by rating is not working in that version. I'm hesitant to change to v0.1.002 as it's a lower version number but I'm assuming it's newer since you uploaded it more recently?

Edit: I switched off the "pre-releases" toggle and clicked the "downgrade" button to go to v0.1.002 and it just gives an error "Unsupported 16-Bit Application" closes the application and breaks the exe. So I guess I'm waiting for a different update.

**Comment by anti-alias-11** [comment]
filtering by rating still doesn't do anything with v0.1.272 also the only option to filter the rating is "Greater than or equal"

**Comment by pornganizer** [comment]
where are you looking?
to filter by rating, use this menu

![image](https://user-images.githubusercontent.com/21695807/102692772-94841d80-41e3-11eb-8345-03f64ad47d61.png)

it offers "Rating more than" and "Rating less than", you open this menu by clicking the magnifying glass beside the search box.

**Comment by anti-alias-11** [comment]
I was trying to use the "additional quick filters" menu where the star graphics are, I missed the one in your image. I probably would have noticed those options if it had the 5 stars graphic like in the quick menu, might be good to change them so they're represented by the star graphics same as in the other menu?

But anyways the rating options in the "additional quick filters" menu don't work.

![additional-filters](https://user-images.githubusercontent.com/74821511/102698550-2157c700-4236-11eb-98fc-05e9288490fa.png)

**Comment by pornganizer** [comment]
fixed in 0.1.279
