### ISSUE TITLE
"Capture frame" issues after latest update.

### ISSUE THREAD

**Issue by anti-alias-11** [pornganizer/PGV5#47]
After updating to v0.1.272 the "Capture frame" functionality in the details pane video player saves the frame to the root directory and shows the image as blank in the details pane.

I've tried manually moving the image to what i assume is the correct directory (where it used to save them in the directory where the video is) but no luck as the path is pointing to where it used to be in the details pane and i can't manually point it to the correct path as far as i know.

Oh i'd also appreciate a direct right click shortcut for deleting frames/screenshots from the hard drive, from the details pane (without having to right click on them going to details and clicking the red bin/trashcan icon)

**Comment by WeedLordVegeta420** [comment]
If you look in the `PgPlayer` section of the Settings, there's an option called `Image Folder` that controls where those screen caps go. Seems like it would be better to have the option to have them go into the same directory with the video. 

Probably very unlikely, but I'm curious what would happen if there was a filename collision with all of the images going into the same directory.

**Comment by pornganizer** [comment]
> If you look in the PgPlayer section of the Settings, there's an option called Image Folder that controls where those screen caps go. Seems like it would be better to have the option to have them go into the same directory with the video.

correct. the latest update improves the location of relevant setttings a bit, i can look into this as well

> Probably very unlikely, but I'm curious what would happen if there was a filename collision with all of the images going into the same directory.

the file name appends _xxx to the end which is the second mark at which the frame was taken. if there is a collision, the original file is replaced.

**Comment by pornganizer** [comment]
can now delete image tags directly from the details pane as of 0.1.280
i'll think about further improvements to image location, perhaps options for PGV5 root, video file location, custom folder
