### ISSUE TITLE
Playback Volume Keeps Resetting to 0%

### ISSUE THREAD

**Issue by sdj88** [pornganizer/PGV5#48]
Hi there,

Willing to make a donation of $50 euro if you're able to help me with my problem as it's been present since the early days of PGV5 thus why I don't really use it. When I select a new file and PGV5 begins playback of the selected video the volume on the slider is always at 0% and I need to keep resetting it back to 50% to hear what is happening every time I start a new video.  

I was also wondering if you will be implementing a feature to increase the speed of which the previewed GIF thumbnails for video files will be implemented? I find that I hover my mouse over the Thumbnail and it takes 3-5 seconds to begin and then it's fairly slow at going through larger videos. 

Many thanks,

**Comment by WeedLordVegeta420** [comment]
I'd honestly throw down another $50+ USD donation for the creator to just open source this. I'm sure this project would have a lot more momentum if there were a way for more people to contribute, and it would also address the privacy/security concerns some people have with using a closed source application for *sensitive* data like this.

**Comment by pornganizer** [comment]
i prefer new videos opening at 0% volume so as to not be taken by surprise by any loud noises right away
i could add a setting to maintain your previous volume, that seems reasonable

you can also adjust the volume using your mouse wheel while your cursor is on the left half of the PgPlayer window

please note that volume will be maintained if you maintain the same PgPlayer window

> I was also wondering if you will be implementing a feature to increase the speed of which the previewed GIF thumbnails for video files will be implemented? I find that I hover my mouse over the Thumbnail and it takes 3-5 seconds to begin and then it's fairly slow at going through larger videos.

this is more related to the specs of your machine and the types of videos you collect. for example, h.265 videos have pretty poor performance generally, hence the preview takes longer to spin up.

**Comment by pornganizer** [comment]
new setting to maintain volume between PgPlayer instances in pre-release v0.1.278
