### ISSUE TITLE
Refine Search

### ISSUE THREAD

**Issue by novo-quinn** [pornganizer/PGV5#51]
Thanks for the app, I really like it. I think it would be really useful to be able to search with "AND" in the search criteria when selecting multiple tags from the same **Category** or **Genre** (same Combo Box), for example:  in the advanced search if I select the Category "BBC", all the scenes involving a BBC will appear but, if in the same search I also include the Category "Creampie", yeah all the BBC scenes with creampies will show up but also ALL non-BBC's scenes that have a creampie will appear too, when I wanted to search only the scenes that **shared** the tags "BBC" **AND** "Creampie", then, if I select another Category, "POV", now the results contain ALL the BBC's, ALL the Creampies and ALL the POV's, so to find a good pov scene with a BBC that also has a creampie is still dificult 'cause I have to manually check every scene to find the ones that contain all three Categories. This also happens when selecting multiple Genres, making the results a _little_ messy. Let me choose to search by "AND" or "OR" when selecting multiple options of the same Combo Box. Also it would be cool to be able to "Not include" or "Ignore" specific tags in the search criteria, example: Give me all the scenes that have "Creampie" AND "BBC" but **ignore** the scenes that have "Anal".

I hope it's not very confusing and if anything of the mentioned above is already included, I'm sorry, but I haven't found it, and again, thank you.

**Comment by pornganizer** [comment]
yes this is an oft requested feature.
AND/OR is complicated enough, without things like ignore and not include.
not only does the UI get pretty complicated but the code is not simple to

it's on my list but it's a tough one

**Comment by pornganizer** [comment]
there is some level of AND and OR in the new version advanced search
for now it will have to do
