### ISSUE TITLE
request: find scenes without a tagged websites/star

### ISSUE THREAD

**Issue by thesowismine** [pornganizer/PGV5#54]
This would be very helpful in figuring out which websites and stars i still need to add.

I thought maybe a workaround might be to just select all scenes from a given website (for stars this would take too long) and mark them "organized", however it does not seem that organized/unorganized labels can be added after selecting multiple scenes.

**Comment by pornganizer** [comment]
i can add this to the advanced search left bar

**Comment by pornganizer** [comment]
fixed in pre-release v0.1.278
