### ISSUE TITLE
Button additive or only

### ISSUE THREAD

**Issue by framedevelop** [pornganizer/PGV5#64]
When one selects an item in the top ribbon it adds/subtracts it to what is displayed rather than selects it as the only item. While you can use the drop down to select only a single item it might be better to have the same capability on the main bar. For example clicking the button “genre, scenes, stars, etc” would select only that item, but selecting a check off box next to the item would be additive or subtractive.

**Comment by pornganizer** [comment]
i think i will add a context menu to each header button that allows you to select that one item and deselect all the rest
