### ISSUE TITLE
Links related to Stars

### ISSUE THREAD

**Issue by zelpi** [pornganizer/PGV5#65]
Can you please make it possible to insert links in the Stars window as it was in PGV4?
Inserting links without direct reference to a star like it's now to me doesn't make much sense...
Thanks...

**Comment by Accho** [comment]
This would be a great feature. PGV4 made it easy to link to a star's pages e.g. OnlyFans, PornHub, ManyVids, etc.

**Comment by pornganizer** [comment]
on my list

**Comment by pornganizer** [comment]
can do this in latest version
