### ISSUE TITLE
Bookmark links overlay on video

### ISSUE THREAD

**Issue by framedevelop** [pornganizer/PGV5#66]
It might be better to left justify the category/bookmarks link overlay instead of center justify because when they are center justified the link keeps moving around based on how many bookmarks/categories exist for that video. Not sure that left justify fixes the problem completely but it might help a little bit rather than having to chase them around when clicking through to videos with the same category.

**Comment by pornganizer** [comment]
i've noticed this myself, its annoying when you are trying to continue clicking through the same category, and the position of the tag you are interested in changes based on the video selected

i dont think justification solves this at all, but i am working on it

**Comment by pornganizer** [comment]
the latest version allows you to limit random videos to specific categories, which avoids this issue. 
i don't have a better solution, going to close this
