### ISSUE TITLE
Adding a Genre from the edit flyout menu does not work

### ISSUE THREAD

**Issue by Accho** [pornganizer/PGV5#68]
If you have a Scene open in the Details Pane and then right click -> edit on a Star then it opens a popup, however if you try to add Genres from within that flyout menu then they get added to the scene currently open in Details Pane and not the Star you chose to edit. Same thing applies to Websites/DVDs/etc

![image](https://user-images.githubusercontent.com/84478854/118887796-b4615f80-b8af-11eb-9b2f-b9fb54fb6148.png)

![image](https://user-images.githubusercontent.com/84478854/118887639-79f7c280-b8af-11eb-8efa-6984e3504c64.png)

**Comment by pornganizer** [comment]
this is never going to be fixed, upgrade to the latest version for proper genre support
