### ISSUE TITLE
how to remove dead files

### ISSUE THREAD

**Issue by TingTingin** [pornganizer/PGV5#71]
if files are moved or changed how to remove dead files from the or links that point to nothing from the file list

**Comment by pornganizer** [comment]
you can relocate the path of a scene in the edit dialog available from the pencil icon in the scene details pane

**Comment by TingTingin** [comment]
I mean if a scene was deleted on the drive side the links to the file still stay in pg even if the file isnt there
is there a way to just delete those

**Comment by pornganizer** [comment]
you can remove links in PG via the delete button in the details pane
unfortunately there is not currently a way to show all dead links, you'll have to search them out manually one by one

**Comment by WeedLordVegeta420** [comment]
> you can relocate the path of a scene in the edit dialog available from the pencil icon in the scene details pane

Have you considered using some sort of hash/checksum to identify files? A lot of similar video applications do this to avoid being totally dependent on an unchanging filepath?

**Comment by pornganizer** [comment]
@WeedLordVegeta420 that is already how PG works

in the advanced search panel you can choose to view files that do not currently exist on disk, and then mass remove them
