### ISSUE TITLE
Request: Improved search and filtering for Bookmarks

### ISSUE THREAD

**Issue by Accho** [pornganizer/PGV5#72]
Currently, if the main display is showing only Bookmarks then the search filters included in the magnifying glass popout do not work. It is not possible to filter Bookmarks by Genre/Website/Star/etc, it is only possible to use the free text search to filter and display Bookmarks of a specific Category.

Ideal state would be to link Bookmarks and Scene info so that it is possible to filter Bookmarks based on how their corresponding Scenes are tagged or rated. 

Additional features such as assigning favorite Bookmarks or giving ratings separate from the overall scene would improve search as well. 

examples of new functionality in this request:
show all Bookmarks for Category A that feature Star X
show all Bookmarks for Category B from Scenes rated with 4 or more stars
show Bookmarks for Category C that are marked as favorite

**Comment by pornganizer** [comment]
bookmark improvements coming soon

**Comment by Accho** [comment]
> bookmark improvements coming soon

Beta looks great so far, I'm loving the new search filters being applied to Bookmarks.
