### ISSUE TITLE
Selecting a cover image for a video doesn't work

### ISSUE THREAD

**Issue by novo-quinn** [pornganizer/PGV5#73]
When selecting a captured frame to display as video cover, it seems to work, but once you click on another video thumbnail and click back the former, the video "chooses" a new cover randomly from the captured frames pool. It also happens when closing and opening the app again; it gives all the videos a random captured frame as cover, ignoring the "Image Set" instruction.

**Comment by pornganizer** [comment]
image sets are dead

currently, for each image you add to a tag, you can choose that it is a display image, ignored, or neither
images will be pulled from images marked as display images, or if there are none any image that is not marked as ignored
