### ISSUE TITLE
Version 0.2.0

### ISSUE THREAD

**Issue by RonBurgundeeznuts** [pornganizer/PGV5#75]
I upgraded to the latest 0.2.0 version from inside the application and it actually installed an older version of PG "0.0.2.0"

Also downloaded directly from github and same result. I did backup and it did an auto backup as well so that's cool. I'm just curious if this is an old build because I haven't seen it before

![image](https://user-images.githubusercontent.com/77546107/149255986-ea177232-769c-4f8c-aa42-461da4574159.png)

![image](https://user-images.githubusercontent.com/77546107/149256376-d4f001c1-f82c-4942-b067-69cefca85f79.png)

**Comment by pornganizer** [comment]
not sure how you managed that. hopefully this is no longer an issue.

**Comment by RonBurgundeeznuts** [comment]
mysteriously fixed
