### ISSUE TITLE
Relocating files added before PGV5 0.2.3.7 Update

### ISSUE THREAD

**Issue by ThatFutaGuy** [pornganizer/PGV5#78]
Currently I am unable relocate any file that was added before updating to the newest version of PG. Any files added after the updated can be relocated freely but any made before it is impossible to relocate them unless they are deleted and re added.

**Comment by pornganizer** [comment]
found an issue with the hashing process in the new version.
i have fixed it in the latest update, but unfortunately it means any scenes added up to this point with the new version have bad hashes and will not be fixed.
