### ISSUE TITLE
Suggestion: Star birthday in homepage

### ISSUE THREAD

**Issue by chicosoquete** [pornganizer/PGV5#79]
Just something that I think could be fun.

I see that in the new homepage (great stuff btw) thare are three "items" autoplaying, one is a link, one is a bookmark and one is a climax. I think it would be fun if the fourth slot is dedicated to a star if it's their birthday. Just the profile pic to not add more stimuli to the page 

I know it's probably not worth the effort because even if its implemented it requires the user to manually add the birthdays at least at this stage, but the database stores a lot of dates by default, maybe "date added" or "last played". Even a random star i think would work (i dont think half the birthdays i found are real anyway), just to change it up a little.

Keep up the good work, this new version is amazing.

**Comment by pornganizer** [comment]
the homepage is currently split into likes, bookmarks, climaxes and links
i see your post is from feb 3, i'm a bit behind 

the latest version uses an API to auto fetch star birthdays when they are created
i like the general birthday idea though, i'll think about it
