### ISSUE TITLE
Object reference not set to an instance of object V2.67 2.68

### ISSUE THREAD

**Issue by chicosoquete** [pornganizer/PGV5#80]
Error reads "Object reference not set to an instance of object", happens to me in versions  V2.67 and 2.68. Latest running version i've got is 2.64

Net framework is up to date.

**Comment by pornganizer** [comment]
are you still having this issue?

i assume it is happening on startup?

can you please provide the full error messages from Windows Event Viewer?

**Comment by chicosoquete** [comment]
yes still happening as of 2.74. on startup it gives this error and wont load the database. i tried creating a fresh database and that works, but wont load my old one that works fine in 2.64.

Cant seem to find the event in event viewer, the timestamps dont match my attempts to open the software, maybe i have to do something to view them?

![obj](https://user-images.githubusercontent.com/98097589/172443695-fbd51cf4-490e-41d0-abb6-febc0aa34a6d.jpg)
![ev](https://user-images.githubusercontent.com/98097589/172444050-353ac2c9-1cc6-4b3e-a8cd-fdc12609d918.png)

**Comment by pornganizer** [comment]
![image](https://user-images.githubusercontent.com/21695807/172445302-291f4bf8-4303-4b1b-b1db-bd74b16230b4.png)
make sure you have this selected

**Comment by chicosoquete** [comment]
![ev2](https://user-images.githubusercontent.com/98097589/172614492-0c0b2429-f1a6-4ce8-8af1-650a2e8699f2.png)
I think the event doesnt get logged, this logged crashes are with version 2.64 but are unrelated to this problem. 
The App doesnt crash when this happens, it just idles there without loading any database, the only thing to do is to close it
![appnothing](https://user-images.githubusercontent.com/98097589/172619174-757320a4-b9a8-4f8c-ab98-73354d451a86.png)

**Comment by pornganizer** [comment]
try deleting 
`C:\Users\YourUserName\AppData\Local\PG`
this folder stores your selected PG preferences. deleting it will restore PG to default configuration.

**Comment by chicosoquete** [comment]
Deleted it but still had the same issue, then i deleted all my links (didn't have many, i just added some to test) and that fixed it, probably a bad link saved  that the new version didn't like. Tanks for all the help and great work.
