### ISSUE TITLE
hover on new ui starts from begining

### ISSUE THREAD

**Issue by TingTingin** [pornganizer/PGV5#81]
In the new UI when you hover over a video it starts previewing from the beginning as opposed the old UI where it would preview random parts of the video similar to how hover on most adult sites work is this intended?

**Comment by pornganizer** [comment]
specifically, how would you like it to behave?

playing random parts of the video doesn't sound great

**Comment by TingTingin** [comment]
The way the old pgv5 hover worked was good it would take a short clip a few secs long then move forward by some amount then do the same basically the same way most adult sites work if you hover over a vid on an adult website that was how I expected it to work

**Comment by pornganizer** [comment]
hm right. i remember this caused issues with shorter videos. i can look into it

**Comment by pornganizer** [comment]
check it out in the latest update

**Comment by TingTingin** [comment]
looks good just have a few critiques 
- Would be nice if it skipped the first few secs or a certain percentage of the video at the beginning so that it skips any intros etc
- Clip length of 5 secs seems a bit long I checked on xvideos and they had it at about 2 secs maybe it shouldn't be as short as but 5 secs seems long
- Instead of a fixed length skip of 45 secs a fixed percentage skip of the video would be better at giving an overview of the video with the current setup if the video has a 5 minute intro the user would have to hover for 35 secs before the intro was over this also is how adult sites generally work

**Comment by TingTingin** [comment]
Hey checked out the latest update saw that the intro skip was added but not some of of the other features just wanted to show a comparison between the old and new UI when it comes to this feature

### OLD
https://thumbs.gfycat.com/UnpleasantPerfectGroundbeetle-mobile.mp4

### CURRENT
https://thumbs.gfycat.com/HonorableSmoggyKingsnake-mobile.mp4

You can see because the skip is a fixed length rather than fixed percentage and the time between skip is longer (I thought the xvideos time between skip of 2 secs would be too short but its around the same amount of time the old UI would skip) in the new version the the video takes really long to actually start and most of the time is spent on the lead up

**Comment by pornganizer** [comment]
hmm ok. ill try and play with the numbers
