### ISSUE TITLE
Star images not showing on main list view

### ISSUE THREAD

**Issue by chicosoquete** [pornganizer/PGV5#83]
I dont know if its just me but star images stopped showing on the main list view. I know the images are a big part of the latest updates so maybe you're already working on it. It's just with the star images, other images from videos categories and genres show just fine.
![st1](https://user-images.githubusercontent.com/98097589/173821319-b199d77a-23a6-4377-87aa-7dc6b8dea32a.png)
it shows them fine in the details and inside the video.
![st2](https://user-images.githubusercontent.com/98097589/173821322-da25e757-8326-45f7-a552-c6fb98c4361a.png)
![st3](https://user-images.githubusercontent.com/98097589/173821324-f43c134f-936a-45be-862a-252eebf63b5c.png)

**Comment by pornganizer** [comment]
ok this is the second report of this occurring now. it seems like on some machines it's showing a single pixel of the actual underlying image. i'll keep looking, i just wish i understood why this is happening only for some people.

**Comment by pornganizer** [comment]
unfortunately i just have not been able to track this down
i created a brand new windows 10 installation and PG does *not* have this issue, which leads me to believe there is something machine specific.

would anyone be willing to allow me temporary remote control of a machine exhibiting this issue? at the moment i'm not sure what else to do

**Comment by pornganizer** [comment]
fixed in 2.87
